# Docker Compose for Testing on Multiple Go versions
version: "3.9"
services:
  v1_14:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile_alpine
      args:
        VARIANT: 1.14
  v1_15:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile_alpine
      args:
        VARIANT: 1.15
  v1_16:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile_alpine
      args:
        VARIANT: 1.16
