name: go1_15

on:
  workflow_dispatch:
  push:

jobs:
  go1_14:
    name: Run on Go v1.15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run on Go 1.15
        run: docker-compose up v1_15
