name: go1_16

on:
  workflow_dispatch:
  push:
  schedule:
    # Runs at 19:30 UTC on Sun (JST: AM 04:30 on every Monday)
    - cron: '30 19 * * SUN'

jobs:
  go1_16:
    name: Run on Go v1.16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run on Go 1.16
        run: docker-compose up v1_16
