name: go1_14

on:
  workflow_dispatch:
  push:
  schedule:
    # Runs at 19:00 UTC on Sun (JST: AM 04:00 on every Monday)
    - cron: '0 19 * * SUN'

jobs:
  go1_14:
    name: Run on Go v1.14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run on Go 1.14
        run: docker-compose up v1_14
