name: go1_15

on:
  workflow_dispatch:
  push:
  schedule:
    # Runs at 19:15 UTC on Sun (JST: AM 04:15 on every Monday)
    - cron: '15 19 * * SUN'

jobs:
  go1_14:
    name: Run on Go v1.15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run on Go 1.15
        run: docker-compose up v1_15
